{
	"id": "oval:com.redhat.cve:def:20243651",
	"version": "636",
	"class": "vulnerability",
	"metadata": {
		"title": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode() (moderate)",
		"reference": [
			{
				"ref_id": "CVE-2024-3651",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2024-3651",
				"source": "CVE"
			}
		],
		"description": "DOCUMENTATION: A flaw was found in the python-idna library. A malicious argument was sent to the idna.encode() function can trigger an uncontrolled resource consumption, resulting in a denial of service.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2024-04-15"
			},
			"cve": [
				{
					"text": "CVE-2024-3651",
					"cvss3": "6.5/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2024-3651",
					"impact": "moderate",
					"public": "20240412"
				}
			],
			"affected": {
				"resolution": [
					{
						"state": "Under investigation",
						"component": [
							"python2-idna"
						]
					}
				]
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openshift:3.11",
					"cpe:/a:redhat:openshift:3.11::el7"
				]
			},
			"issued": {}
		},
		"affected": {}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:com.redhat.cve:tst:20130169005",
						"comment": "Red Hat Enterprise Linux 7 is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:20243651001",
						"comment": "python2-idna is installed"
					},
					{
						"test_ref": "oval:com.redhat.cve:tst:20243651002",
						"comment": "python2-idna is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20130169006",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
