{
	"id": "oval:com.redhat.rhsa:def:20201324",
	"version": "634",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2020:1324: python-django security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2020:1324",
				"ref_url": "https://access.redhat.com/errata/RHSA-2020:1324",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2019-12781",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-12781",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2019-14232",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-14232",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2019-14233",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-14233",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2019-14234",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-14234",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2019-14235",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-14235",
				"source": "CVE"
			}
		],
		"description": "Django is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\n\nSecurity Fix(es):\n\n* Incorrect HTTP detection with reverse-proxy connecting via HTTPS\n(CVE-2019-12781)\n\n* backtracking in a regular expression in django.utils.text.Truncator leads\nto DoS (CVE-2019-14232)\n\n* the behavior of the underlying HTMLParser leading to DoS (CVE-2019-14233)\n\n* SQL injection possibility in key and index lookups for\nJSONField/HStoreField (CVE-2019-14234)\n\n* Potential memory exhaustion in django.utils.encoding.uri_to_iri()\n(CVE-2019-14235)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2020-04-06"
			},
			"cve": [
				{
					"text": "CVE-2019-12781",
					"cvss3": "4.8/CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N",
					"cwe": "(CWE-358|CWE-444)",
					"href": "https://access.redhat.com/security/cve/CVE-2019-12781",
					"impact": "moderate",
					"public": "20190701"
				},
				{
					"text": "CVE-2019-14232",
					"cvss3": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"cwe": "CWE-20",
					"href": "https://access.redhat.com/security/cve/CVE-2019-14232",
					"impact": "moderate",
					"public": "20190801:0800"
				},
				{
					"text": "CVE-2019-14233",
					"cvss3": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"cwe": "CWE-20",
					"href": "https://access.redhat.com/security/cve/CVE-2019-14233",
					"impact": "moderate",
					"public": "20190801:0800"
				},
				{
					"text": "CVE-2019-14234",
					"cvss3": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
					"cwe": "CWE-20",
					"href": "https://access.redhat.com/security/cve/CVE-2019-14234",
					"impact": "moderate",
					"public": "20190801:0800"
				},
				{
					"text": "CVE-2019-14235",
					"cvss3": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
					"cwe": "CWE-400",
					"href": "https://access.redhat.com/security/cve/CVE-2019-14235",
					"impact": "moderate",
					"public": "20190801:0800"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:openstack:15",
					"cpe:/a:redhat:openstack:15::el8"
				]
			},
			"rights": "Copyright 2020 Red Hat, Inc.",
			"issued": {
				"date": "2020-04-06"
			},
			"bugzilla": [
				{
					"text": "Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
					"href": "https://bugzilla.redhat.com/1724497",
					"id": "1724497"
				},
				{
					"text": "Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS",
					"href": "https://bugzilla.redhat.com/1734405",
					"id": "1734405"
				},
				{
					"text": "Django: the behavior of the underlying HTMLParser leading to DoS",
					"href": "https://bugzilla.redhat.com/1734410",
					"id": "1734410"
				},
				{
					"text": "Django: SQL injection possibility in key and index lookups for JSONField/HStoreField",
					"href": "https://bugzilla.redhat.com/1734417",
					"id": "1734417"
				},
				{
					"text": "Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()",
					"href": "https://bugzilla.redhat.com/1734422",
					"id": "1734422"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat OpenStack Platform 15.0 (Stein)"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.cve:tst:20159543029",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhsa:tst:20194358006",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20201324001",
										"comment": "python-django-bash-completion is earlier than 0:2.1.11-1.el8ost"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844002",
										"comment": "python-django-bash-completion is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20201324003",
										"comment": "python3-django is earlier than 0:2.1.11-1.el8ost"
									},
									{
										"test_ref": "oval:com.redhat.cve:tst:201919844004",
										"comment": "python3-django is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.cve:tst:20159543030",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
