{
	"id": "oval:com.redhat.rhsa:def:20214324",
	"version": "635",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2021:4324: python-psutil security update (Moderate)",
		"reference": [
			{
				"ref_id": "RHSA-2021:4324",
				"ref_url": "https://access.redhat.com/errata/RHSA-2021:4324",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2019-18874",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2019-18874",
				"source": "CVE"
			}
		],
		"description": "psutil is a module providing an interface for retrieving information on all running processes and system utilization (CPU, memory, disks, network, users) in a portable way by using Python.\n\nSecurity Fix(es):\n\n* python-psutil: double free because of refcount mishandling (CVE-2019-18874)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Red Hat Enterprise Linux 8.5 Release Notes linked from the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Moderate",
			"updated": {
				"date": "2021-11-09"
			},
			"cve": [
				{
					"text": "CVE-2019-18874",
					"cvss3": "7.0/CVSS:3.0/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
					"cwe": "CWE-416",
					"href": "https://access.redhat.com/security/cve/CVE-2019-18874",
					"impact": "moderate",
					"public": "20191107"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_tus:8.8",
					"cpe:/a:redhat:rhel_tus:8.8::appstream",
					"cpe:/a:redhat:rhel_tus:8.8::highavailability",
					"cpe:/a:redhat:rhel_tus:8.8::nfv",
					"cpe:/a:redhat:rhel_tus:8.8::realtime",
					"cpe:/o:redhat:rhel_tus:8.8",
					"cpe:/o:redhat:rhel_tus:8.8::baseos"
				]
			},
			"rights": "Copyright 2021 Red Hat, Inc.",
			"issued": {
				"date": "2021-11-09"
			},
			"bugzilla": [
				{
					"text": "CVE-2019-18874 python-psutil: Double free because of refcount mishandling",
					"href": "https://bugzilla.redhat.com/1772014",
					"id": "1772014"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20214324001",
						"comment": "python3-psutil is earlier than 0:5.4.3-11.el8"
					},
					{
						"test_ref": "oval:com.redhat.rhsa:tst:20214324002",
						"comment": "python3-psutil is signed with Red Hat redhatrelease2 key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20191992005",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
