{
  "id": "oval:com.redhat.cve:def:202029651",
  "version": "636",
  "class": "vulnerability",
  "metadata": {
    "title": "CVE-2020-29651 python-py: ReDoS in the py.path.svnwc component via mailicious input to blame functionality (low)",
    "reference": [
      {
        "ref_id": "CVE-2020-29651",
        "ref_url": "https://access.redhat.com/security/cve/CVE-2020-29651",
        "source": "CVE"
      }
    ],
    "description": "DOCUMENTATION: The MITRE CVE dictionary describes this issue as: A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality. \n            STATEMENT: In Red Hat OpenStack Platform, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-py package.",
    "advisory": {
      "from": "secalert@redhat.com",
      "severity": "Low",
      "updated": {
        "date": "2021-10-28"
      },
      "cve": [
        {
          "text": "CVE-2020-29651",
          "cvss3": "4.3/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
          "cwe": "CWE-20->CWE-400",
          "href": "https://access.redhat.com/security/cve/CVE-2020-29651",
          "impact": "low",
          "public": "20200903"
        }
      ],
      "affected": {
        "resolution": [
          {
            "state": "Out of support scope",
            "component": [
              "python-py"
            ]
          }
        ]
      },
      "affected_cpe_list": {
        "cpe": [
          "cpe:/a:redhat:rhel_extras:7",
          "cpe:/a:redhat:rhel_extras_oracle_java:7",
          "cpe:/a:redhat:rhel_extras_rt:7",
          "cpe:/a:redhat:rhel_extras_sap:7",
          "cpe:/a:redhat:rhel_extras_sap_hana:7",
          "cpe:/o:redhat:enterprise_linux:7",
          "cpe:/o:redhat:enterprise_linux:7::client",
          "cpe:/o:redhat:enterprise_linux:7::computenode",
          "cpe:/o:redhat:enterprise_linux:7::container",
          "cpe:/o:redhat:enterprise_linux:7::containers",
          "cpe:/o:redhat:enterprise_linux:7::server",
          "cpe:/o:redhat:enterprise_linux:7::workstation"
        ]
      },
      "issued": {}
    },
    "affected": {}
  },
  "criteria": {
    "operator": "OR",
    "criterias": [
      {
        "operator": "AND",
        "criterions": [
          {
            "test_ref": "oval:com.redhat.cve:tst:20042779005",
            "comment": "Red Hat Enterprise Linux 7 is installed"
          },
          {
            "test_ref": "oval:com.redhat.cve:tst:202029651001",
            "comment": "python-py is installed"
          },
          {
            "test_ref": "oval:com.redhat.cve:tst:202029651002",
            "comment": "python-py is signed with Red Hat redhatrelease2 key"
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:com.redhat.cve:tst:20042779006",
        "comment": "Red Hat Enterprise Linux must be installed"
      }
    ]
  }
}
