{
	"id": "oval:com.redhat.rhsa:def:20203658",
	"version": "635",
	"class": "patch",
	"metadata": {
		"title": "RHSA-2020:3658: librepo security update (Important)",
		"reference": [
			{
				"ref_id": "RHSA-2020:3658",
				"ref_url": "https://access.redhat.com/errata/RHSA-2020:3658",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2020-14352",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2020-14352",
				"source": "CVE"
			}
		],
		"description": "The librepo library provides a C and Python API to download repository metadata.\n\nSecurity Fix(es):\n\n* librepo: missing path validation in repomd.xml may lead to directory traversal (CVE-2020-14352)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Important",
			"updated": {
				"date": "2020-09-08"
			},
			"cve": [
				{
					"text": "CVE-2020-14352",
					"cvss3": "8.0/CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H",
					"cwe": "CWE-22",
					"href": "https://access.redhat.com/security/cve/CVE-2020-14352",
					"impact": "important",
					"public": "20200813"
				}
			],
			"affected": {},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/a:redhat:rhel_eus:8.8",
					"cpe:/a:redhat:rhel_eus:8.8::appstream",
					"cpe:/a:redhat:rhel_eus:8.8::crb",
					"cpe:/a:redhat:rhel_eus:8.8::highavailability",
					"cpe:/a:redhat:rhel_eus:8.8::nfv",
					"cpe:/a:redhat:rhel_eus:8.8::realtime",
					"cpe:/a:redhat:rhel_eus:8.8::resilientstorage",
					"cpe:/a:redhat:rhel_eus:8.8::sap",
					"cpe:/a:redhat:rhel_eus:8.8::sap_hana",
					"cpe:/a:redhat:rhel_eus:8.8::supplementary",
					"cpe:/o:redhat:rhel_eus:8.8",
					"cpe:/o:redhat:rhel_eus:8.8::baseos"
				]
			},
			"rights": "Copyright 2020 Red Hat, Inc.",
			"issued": {
				"date": "2020-09-08"
			},
			"bugzilla": [
				{
					"text": "CVE-2020-14352 librepo: missing path validation in repomd.xml may lead to directory traversal",
					"href": "https://bugzilla.redhat.com/1866498",
					"id": "1866498"
				}
			]
		},
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 8"
			]
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterions": [
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992003",
								"comment": "Red Hat Enterprise Linux 8 is installed"
							},
							{
								"test_ref": "oval:com.redhat.rhba:tst:20191992004",
								"comment": "Red Hat CoreOS 4 is installed"
							}
						]
					},
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20203658001",
										"comment": "librepo is earlier than 0:1.11.0-3.el8_2"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20193583040",
										"comment": "librepo is signed with Red Hat redhatrelease2 key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20203658003",
										"comment": "python3-librepo is earlier than 0:1.11.0-3.el8_2"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20193583042",
										"comment": "python3-librepo is signed with Red Hat redhatrelease2 key"
									}
								]
							}
						]
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20191992005",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
