{
  "id": "oval:com.redhat.cve:def:202329824",
  "version": "636",
  "class": "vulnerability",
  "metadata": {
    "title": "scipy: use-after-free in Py_FindObjects() function (moderate)",
    "reference": [
      {
        "ref_id": "CVE-2023-29824",
        "ref_url": "https://access.redhat.com/security/cve/CVE-2023-29824",
        "source": "CVE"
      }
    ],
    "description": "DOCUMENTATION: A flaw was found in SciPy, where it is vulnerable to a denial of service caused by a use-after-free bug in the Py_FindObjects() function. By sending a specially crafted request, an attacker can cause a denial of service condition. \n            STATEMENT: This CVE is disputed as per upstream - https://github.com/scipy/scipy/issues/14713#issuecomment-1629468565",
    "advisory": {
      "from": "secalert@redhat.com",
      "severity": "Moderate",
      "updated": {
        "date": "2023-10-31"
      },
      "cve": [
        {
          "text": "CVE-2023-29824",
          "cvss3": "7.0/CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H",
          "cwe": "CWE-416",
          "href": "https://access.redhat.com/security/cve/CVE-2023-29824",
          "impact": "moderate",
          "public": "20230706"
        }
      ],
      "affected": {
        "resolution": [
          {
            "state": "Will not fix",
            "component": [
              "python3-scipy",
              "python3.11-scipy"
            ]
          }
        ]
      },
      "affected_cpe_list": {
        "cpe": [
          "cpe:/a:redhat:enterprise_linux:9",
          "cpe:/a:redhat:enterprise_linux:9::appstream",
          "cpe:/a:redhat:enterprise_linux:9::crb",
          "cpe:/a:redhat:enterprise_linux:9::highavailability",
          "cpe:/a:redhat:enterprise_linux:9::nfv",
          "cpe:/a:redhat:enterprise_linux:9::realtime",
          "cpe:/a:redhat:enterprise_linux:9::resilientstorage",
          "cpe:/a:redhat:enterprise_linux:9::sap",
          "cpe:/a:redhat:enterprise_linux:9::sap_hana",
          "cpe:/a:redhat:enterprise_linux:9::supplementary",
          "cpe:/o:redhat:enterprise_linux:9",
          "cpe:/o:redhat:enterprise_linux:9::baseos"
        ]
      },
      "issued": {}
    },
    "affected": {}
  },
  "criteria": {
    "operator": "OR",
    "criterias": [
      {
        "operator": "AND",
        "criterias": [
          {
            "operator": "OR",
            "criterias": [
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202325399003",
                    "comment": "python3-scipy is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202325399004",
                    "comment": "python3-scipy is signed with Red Hat redhatrelease2 key"
                  }
                ]
              },
              {
                "operator": "AND",
                "criterions": [
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202325399001",
                    "comment": "python3.11-scipy is installed"
                  },
                  {
                    "test_ref": "oval:com.redhat.cve:tst:202325399002",
                    "comment": "python3.11-scipy is signed with Red Hat redhatrelease2 key"
                  }
                ]
              }
            ]
          }
        ],
        "criterions": [
          {
            "test_ref": "oval:com.redhat.cve:tst:20052541003",
            "comment": "Red Hat Enterprise Linux 9 is installed"
          }
        ]
      }
    ],
    "criterions": [
      {
        "test_ref": "oval:com.redhat.cve:tst:20052541004",
        "comment": "Red Hat Enterprise Linux must be installed"
      }
    ]
  }
}
